name: .NET 5 Build and Test

on:
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Add GitHub Packages for Nuget
      run: dotnet nuget add source https://nuget.pkg.github.com/bassclefstudio/index.json --name "GPR" --username bassclefstudio --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    - name: Install dependencies
      run: |
        dotnet restore ./BassClefStudio.Graphics/BassClefStudio.Graphics.csproj
        dotnet restore ./BassClefStudio.Graphics.Tests/BassClefStudio.Graphics.Tests.csproj
    - name: Build
      run: |
        dotnet build ./BassClefStudio.Graphics/BassClefStudio.Graphics.csproj --configuration Release --no-restore
        dotnet build ./BassClefStudio.Graphics.Tests/BassClefStudio.Graphics.Tests.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test ./BassClefStudio.Graphics.Tests/BassClefStudio.Graphics.Tests.csproj --no-restore --verbosity normal